name: Formats

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest

        php: [8.4]
    name: Formats P8.4 - ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        extensions: dom, mbstring, zip
        coverage: pcov

    - name: Get Composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: dependencies-php-8.4-os-ubuntu-latest-composer-${{ hashFiles('composer.json') }}
        restore-keys: dependencies-php-8.4-os-ubuntu-latest-composer-

    - name: Install Composer dependencies
      run: composer update --prefer-stable --no-interaction --prefer-dist

    - name: Coding Style Checks
      run: composer test:lint

    - name: Type Checks
      run: composer test:types

    - name: Type Coverage Checks
      run: composer test:type-coverage

    - name: Typo Checks
      run: composer test:typos

    - name: Refactor Checks
      run: composer test:refactor
